[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "Shougo/vimproc.vim"
build = "make"

[[plugins]]
repo = "autozimu/LanguageClient-neovim"
rev = "next"
build = "bash install.sh"
hook_add = """
  set hidden
  let g:LanguageClient_serverCommands = {
    \ "python": ["pyls"],
    \ "haskell": ["hie-wrapper"],
    \ }
  let g:LanguageClient_autoStart = 1
  let g:LanguageClient_diagnosticsEnable = 0

  if &filetype == "haskell"
    let g:LanguageClient_rootMarkers = ["*.cabal", "stack.yaml"]
  endif

  nnoremap <silent> gt :call LanguageClient_textDocument_hover()<CR>
  nnoremap <silent> gr :call LanguageClient_textDocument_rename()<CR>
  nnoremap <silent> gs :call LanugageClient_textDocument_documentSymbol()<CR>
  nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
  nnoremap <silent> gr :call LanguageClient_textDocument_rename()<CR>
  nnoremap <silent> g- :call LanguageClient_textDocument_formatting()<CR>
"""

[[plugins]]
repo = "liuchengxu/vista.vim"
depends = ["LanguageClient-neovim"]

[[plugins]]
repo = "Yggdroot/indentLine"
hook_add = """
  let g:indentLine_char = '¦'
  let g:indentLine_fileTypeExclude = ["help", "nerdtree", "calendar", "haskell"]
"""

[[plugins]]
repo = "tomtom/tcomment_vim"

[[plugins]]
repo = "tpope/vim-surround"

[[plugins]]
repo = "Shougo/context_filetype.vim"

[[plugins]]
repo = "osyo-manga/vim-precious"
depends = ["context_filetype.vim"]

[[plugins]]
repo = "w0rp/ale"
hook_add = """
  let g:ale_sign_error = "⨉"
  let g:ale_sign_warning = "⚠"
  let g:ale_statusline_format = ["⨉ %d", "⚠ %d", "⬥ ok"]
  let g:ale_echo_msg_format = "[%linter%] %s [%severity%]"
  let g:ale_sign_column_always = 1
  " let g:ale_lint_on_enter = 1
  " let g:ale_lint_on_text_changed = 1
  let g:ale_linters = {
    \ "python": ["flake8"],
    \ }
"""

[[plugins]]
repo = "tpope/vim-repeat"

[[plugins]]
repo = "jiangmiao/auto-pairs"

[[plugins]]
repo = "yuttie/comfortable-motion.vim"

[[plugins]]
repo = "itchyny/vim-cursorword"

[[plugins]]
repo = "bronson/vim-trailing-whitespace"
hook_add = """
  let g:extra_whitespace_ignored_filetypes = []
"""
