[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "Shougo/vimproc.vim"
build = "make"

[[plugins]]
repo = "neoclide/coc.nvim"
rev = "release"
merged = "0"
"hook_add" = """
  set updatetime = 300
"""

[[plugins]]
repo = "liuchengxu/vista.vim"
depends = ["coc.nvim"]

[[plugins]]
repo = "Yggdroot/indentLine"
hook_add = """
  let g:indentLine_char = '¦'
  let g:indentLine_fileTypeExclude = ["help", "nerdtree", "calendar", "haskell"]
"""

[[plugins]]
repo = "tomtom/tcomment_vim"

[[plugins]]
repo = "tpope/vim-surround"

[[plugins]]
repo = "Shougo/context_filetype.vim"

[[plugins]]
repo = "osyo-manga/vim-precious"
depends = ["context_filetype.vim"]

[[plugins]]
repo = "tpope/vim-repeat"

[[plugins]]
repo = "jiangmiao/auto-pairs"

[[plugins]]
repo = "yuttie/comfortable-motion.vim"

[[plugins]]
repo = "itchyny/vim-cursorword"

[[plugins]]
repo = "bronson/vim-trailing-whitespace"
hook_add = """
  let g:extra_whitespace_ignored_filetypes = []
"""
