[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "Shougo/vimproc.vim"
build = "make"

[[plugins]]
repo = "autozimu/LanguageClient-neovim"
rev = "next"
build = "./install.sh"
hook_add = """
  set hidden
  let g:LanguageClient_serverCommands = {
    \ "python": ["pyls"],
    \ "haskell": ["hie"]
    \ }
  let g:LanguageClient_autoStart = 1
  let g:LanguageClient_diagnosticsEnable = 0
"""

[[plugins]]
repo = "Shougo/neosnippet-snippets"

[[plugins]]
repo = "Yggdroot/indentLine"
hook_add = """
  let g:indentLine_char = '¦'
"""

[[plugins]]
repo = "scrooloose/nerdtree"
hook_add = """
  autocmd StdinReadPre * let s:std_in=1
  autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
  nnoremap <silent><C-e> :NERDTreeToggle<CR>
"""

[[plugins]]
repo = "tomtom/tcomment_vim"

[[plugins]]
repo = "tpope/vim-surround"

[[plugins]]
repo = "alvan/vim-closetag"

[[plugins]]
repo = "jiangmiao/auto-pairs"

[[plugins]]
repo = "thinca/vim-quickrun"

[[plugins]]
repo = "Shougo/context_filetype.vim"

[[plugins]]
repo = "osyo-manga/vim-precious"
depends = ["context_filetype.vim"]

[[plugins]]
repo = "w0rp/ale"
hook_add = """
  let g:ale_sign_error = "⨉"
  let g:ale_sign_warning = "⚠"
  let g:ale_statusline_format = ["⨉ %d", "⚠ %d", "⬥ ok"]
  let g:ale_echo_msg_format = "[%linter%] %s [%severity%]"
  let g:ale_sign_column_always = 1
  let g:ale_lint_on_enter = 1
  let g:ale_linters = {
    \ "python": ["flake8"],
    \ "haskell": ["hie"]
    \ }
"""

[[plugins]]
repo = "itchyny/calendar.vim"

[[plugins]]
repo = "Kantouzin/vim-today"

[[plugins]]
repo = "Kantouzin/vim-formatted-title"
hook_add = """
  let g:formattedTitle_char = '='
  let g:formattedTitle_title_len = 30
"""

[[plugins]]
repo = "tpope/vim-repeat"

[[plugins]]
repo = "yuttie/comfortable-motion.vim"

[[plugins]]
repo = "osyo-manga/vim-over"
hook_add = """
  nnoremap <silent> <Space>// :OverCommandLine<CR>%s/
"""
