
[[plugins]]
repo = "eagletmt/ghcmod-vim"
on_ft = ["haskell"]
hook_source = """
  :command Gt GhcModType

  augroup ghcmodcheck
    autocmd! BufWritePost <buffer> GhcModCheckAsync
  augroup END
"""

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = ["haskell"]

[[plugins]]
repo = "itchyny/vim-haskell-indent"
on_ft = ["haskell"]

[[plugins]]
repo = "cespare/vim-toml"
on_ft = ["toml"]
