[[plugins]]
repo = 'SirVer/ultisnips'
on_event = ['InsertEnter']
hook_add = '''
  let g:UltiSnipsExpandTrigger="<c-k>"
  let g:UltiSnipsJumpForwardTrigger="<c-k>"
  let g:UltiSnipsJumpBackwardTrigger="<c-z>"
'''

[[plugins]]
repo = 'honza/vim-snippets'
on_event = ['InsertEnter']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']
hook_add = '''
  autocmd StdinReadPre * let s:std_in=1
  autocmd VimEnter * if argc() == 0 && !exists('s:std_in') | NERDTree | endif
  nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']

[[plugins]]
repo = 'itchyny/calendar.vim'
on_cmd = ['Calendar']

[[plugins]]
repo = 'osyo-manga/vim-over'
on_cmd = ['OverCommandLine']
hook_add = '''
  nnoremap <silent> <Space>// :OverCommandLine<CR>%s/
'''

[[plugins]]
repo = 'Kantouzin/vim-today'
on_cmd = ['Today']

[[plugins]]
repo = 'Kantouzin/vim-formatted-title'
on_cmd = ['FormattedTitle']
hook_source = '''
  let g:formattedTitle_char = '='
  let g:formattedTitle_title_len = 30
'''

[[plugins]]
repo = 'junegunn/goyo.vim'
hook_source = '''
  let g:goyo_width = 80%
'''
on_cmd = ['Goyo']
