[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_event = ['InsertEnter']
on_ft = ['haskell']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_event = ['InsertEnter']
on_ft = ['python']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_source = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'alunny/pegjs-vim'
on_ft = ['pegjs']

[[plugins]]
repo = 'alvan/vim-closetag'
on_event = ['InsertEnter']
on_ft = ['html', 'xhtml', 'xml']

[[plugins]]
repo = 'voldikss/vim-wenyan'
on_ft = ['wenyan']

[[plugins]]
repo = 'ollykel/v-vim'
on_ft = ['vlang']

[[plugins]]
repo = 'vim-scripts/VimClojure'
on_ft = ['clojure']
hook_source = '''
  let g:vimclojure#HighlightBuiltins=1
  let g:vimclojure#HighlightContrib=1
  let g:vimclojure#DynamicHighlighting=1
  let g:vimclojure#ParenRainbow=1
'''

[[plugins]]
repo = 'vim-scripts/vpp.vim'
on_ft = ['vpp']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
