[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "Shougo/vimproc.vim"
build = "make"

[[plugins]]
repo = "nathanaelkane/vim-indent-guides"
hook_add = """
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_guide_size = 1
"""

[[plugins]]
repo = "scrooloose/nerdtree"

[[plugins]]
repo = "tomtom/tcomment_vim"

[[plugins]]
repo = "tpope/vim-surround"
